### ISSUE TITLE
How to Managing MRB_STATE

### ISSUE THREAD

**Issue by keizo042** [KeizoBookman/libvmod_mruby#7]
we need to manage mrb_state.but, i can not find vcl_recv hook, c level.
how can i manage states?
i thing one way.

```
vcl_init{
mruby.init $CONFIG_PATH;
}
vcl_recv{
mruby.add
}
vcl_deliver{
mruby.close
}
```

but, it is lame.
i thing cool that like

```
vcl_init {
 mruby.conf_init $CONFIG_PATH;
}
```

**Comment by keizo042** [comment]
sample implementation origin/bridge2.
https://github.com/KeizoBookman/libvmod_mruby/commit/1fe90e1cfa3eaa525510c0186b8e24d5873fbdaa

**Comment by KeizoBookman** [comment]
https://github.com/KeizoBookman/libvmod_mruby/commit/1fe90e1cfa3eaa525510c0186b8e24d5873fbdaa

**Comment by keizo042** [comment]
now, as follow

```
vcl_init {
mruby.init();
}

vcl_recv {
 mruby.handler(CONF_PATH);
}
```
